spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://bohemia:3306/estoque?useSSL=false&serverTimezone=America/Sao_Paulo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: estoque
    password: 4Getit..


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

cors:
  allowed-origins: http://localhost:5173
