spring:
  profiles:
    active: dev
  jackson:
    time-zone: America/Sao_Paulo

  liquibase:
    change-log: classpath:db/changelog-master.xml

jwt:
  secret: xJ8D+U6f49Pd2sC6TzJ7oXv6nE1aBqYFgk3gNvp+E4M=
